name: Blue-Green Deployment with WIF

on:
  push:
    branches:
      - main

env:
  K8S_NAMESPACE: default

permissions:
  id-token: write      
  contents: read  
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate using WIF
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/1019578273090/locations/global/workloadIdentityPools/test-git/providers/testing-jit"
          service_account: "sb-test@sachinsoni.iam.gserviceaccount.com"
          
      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q
          gcloud components update -q

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials test-cluster \
            --zone us-central1-a \
            --project sachinsoni

      - name: Get current version
        id: get-version
        run: |
          CURRENT_VERSION=$(kubectl get service my-service -n ${{ env.K8S_NAMESPACE }} -o jsonpath='{.spec.selector.version}')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Deploy new version
        env:
          CURRENT_VERSION: ${{ steps.get-version.outputs.current_version }}
          NEW_VERSION: ${{ steps.get-version.outputs.current_version == 'blue' && 'green' || 'blue' }}
        run: |
          # Deploy new version
          envsubst < test-bg/deployment-${NEW_VERSION}.yaml | kubectl apply -f -
          
          # Wait for deployment to be ready
          kubectl rollout status deployment/${NEW_VERSION} -n ${{ env.K8S_NAMESPACE }}
          
          # Switch traffic to new version
          kubectl patch service my-service -n ${{ env.K8S_NAMESPACE }} --type='json' -p='[{"op": "replace", "path": "/spec/selector/version", "value":"'${NEW_VERSION}'"}]'
          
          # Wait for service to stabilize
          sleep 30
          
          # Delete old version
          kubectl delete deployment ${CURRENT_VERSION} -n ${{ env.K8S_NAMESPACE }}
      








#------------------------------------------------------------------------------------------------





# name: "Terraform CI"

# on:
#   push:
#     branches:
#       - "feature/**"
#       - main
#   pull_request:
  
#   repository_dispatch:
#     types: 
#       - trigger-gitops
# jobs:
#   terraform:
#     name: "Terraform"
#     runs-on: ubuntu-latest
#     permissions:
#       contents: "write"
#       id-token: "write"
#     env:
#       WORKING_DIRECTORY_1: gp-vending
#       WORKING_DIRECTORY_2: sandbox-vending
#       GITHUB_TOKEN: ${{ secrets.DEMO_CLEANUP }}

#     defaults:
#       run:
#         shell: bash

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Set Google Cloud credentials
#         uses: "google-github-actions/auth@v2"
#         with:
#           service_account: "sb-test@sachinsoni.iam.gserviceaccount.com"
#           workload_identity_provider: "projects/1019578273090/locations/global/workloadIdentityPools/test-git/providers/testing-jit"

#       - name: Run Cleanup Script
#         id: cleanup
#         run: |
#           chmod +x deletion_script.sh
#           OUTPUT=$(./deletion_script.sh)
#           echo "$OUTPUT"
#           if [[ "$OUTPUT" == *"File deletion process completed. No files were deleted."* ]]; then
#             echo "deletion_occurred=false" >> $GITHUB_ENV
#           else
#             echo "deletion_occurred=true" >> $GITHUB_ENV
#           fi
#         env:
#           GITHUB_TOKEN: ${{ secrets.DEMO_CLEANUP }}

#       - name: Initialize Terraform for gp-vending
#         if: env.deletion_occurred == 'false'
#         run: |
#           echo "Initializing Terraform in directory: ${{ env.WORKING_DIRECTORY_1 }}"
#           terraform init
#         working-directory: ${{ env.WORKING_DIRECTORY_1 }}
        
#       - name: Format Terraform for gp-vending
#         if: env.deletion_occurred == 'false'
#         run: |
#           echo "Formatting Terraform in directory: ${{ env.WORKING_DIRECTORY_1 }}"
#           terraform fmt -check
#         working-directory: ${{ env.WORKING_DIRECTORY_1 }}
      
#       - name: Plan Terraform for gp-vending
#         if: env.deletion_occurred == 'false'
#         run: |
#           echo "Planning Terraform in directory: ${{ env.WORKING_DIRECTORY_1 }}"
#           terraform plan
#         working-directory: ${{ env.WORKING_DIRECTORY_1 }}
      
#       # - name: Apply Terraform for gp-vending
#       #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.deletion_occurred == 'false'
#       #   run: |
#       #     echo "Applying Terraform in directory: ${{ env.WORKING_DIRECTORY_1 }}"
#       #     terraform apply -auto-approve
#       #   working-directory: ${{ env.WORKING_DIRECTORY_1 }}

#       - name: Initialize Terraform for sandbox-vending
#         if: env.deletion_occurred == 'false'
#         run: |
#           echo "Initializing Terraform in directory: ${{ env.WORKING_DIRECTORY_2 }}"
#           terraform init
#         working-directory: ${{ env.WORKING_DIRECTORY_2 }}

      
#       - name: Format Terraform for sandbox-vending
#         if: env.deletion_occurred == 'false'
#         run: |
#           echo "Formatting Terraform in directory: ${{ env.WORKING_DIRECTORY_2 }}"
#           terraform fmt -check
#         working-directory: ${{ env.WORKING_DIRECTORY_2 }}

#       - name: Plan Terraform for sandbox-vending
#         if: env.deletion_occurred == 'false'
#         run: |
#           echo "Planning Terraform in directory: ${{ env.WORKING_DIRECTORY_2 }}"
#           terraform plan
#         working-directory: ${{ env.WORKING_DIRECTORY_2 }}

#       # - name: Apply Terraform for sandbox-vending
#       #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.deletion_occurred == 'false'
#       #   run: |
#       #     echo "Applying Terraform in directory: ${{ env.WORKING_DIRECTORY_2 }}"
#       #     terraform apply -auto-approve
#       #   working-directory: ${{ env.WORKING_DIRECTORY_2 }}
